apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: sample-python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-python-app
  template:
    metadata:
      labels:
        app: sample-python-app
    spec:
      containers:
      - name: py-app
        image: sample_py_app:v1
        ports:
        - containerPort: 8000

