apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx4
  namespace: default
  labels:
    app:  nginx
    team: IN
    env: Dev
spec:
  selector:
    matchLabels:
      app: nginx
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
      - {key: team, operator: In, values: [IN]}
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        team: IN
        env: Dev
        tier: frontend
    spec:
      volumes:
        - name: my-pvc-storage
          persistentVolumeClaim:
            claimName: my-pvc
      containers:
      - name:  nginx
        image:  httpd:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  80
        volumeMounts:
          - mountPath: "/usr/local/apache2/htdocs"
            name: my-pvc-storage
---
