apiVersion: v1
kind: Pod
metadata:
  name: "myapp"
  namespace: default
  labels:
    app: "myapp"
spec:
  containers:
  - name: myapp
    image: "httpd:latest"
    ports:
    - containerPort: 80
      name:  http
---

