apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app: nginx
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/d/PVC/"
