apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  labels:
    app: nginx
spec:
  storageClassName: ""
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
