apiVersion: v1
kind: Service
metadata:
  name: my-python-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/app: flaskp
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
